apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB4u2AP0XLMKAbDS8dye7LhyYCoqtWFegyIslHGADr3DoCtRhrRgOsMvLl0byo8UcAS5H1quYC4v+XirL0uykM7fLEmjOhsq8Zm3MRVIpbliBWXYI7bnxuUs1Gh+Y7VSBuGlJyX68cXtYSc1wvzDRkCa4gs+KNeZPHiEFuXPb1QCEyhE87TpN14qQZetogiai5PqrDczbzGZQS3ymA54Rh1gp/l0H/TiUj5EYYJUfdx+bEItA+OMSCyi7rTP989S6aCUxuJKg9ReCHs1whYyoduKerqKKHnzB1+yNqqkr5/Edu46K0d6Fl21h4VlYJc1tio/xyPoWq/K4bv74hhEFiPVMJ0V12zAauaA7rpPxNOnJJsS8krrLk4ZDCcEtlw8pCNaOecG7lUPOSn6e4ZIwxHc69fg8sBko4CxKSDwy1H9GdocLQswpdLv48464GWIXb1rOHv4dXbbNryCSPY3LfIM6KE0DZUymmK88oTOLD5YpmtQnvfa/BaWe1zzy53tFwTyMV490SdTNz+aIDkMLaNmmjpt8hTN4k/0QaGf750McPmgYxqn2Y3el1MF31dN1y4wwBG0CVtiNgn5Roa3/PDN1HmEXCklo31rpxOiAmsUpG4lFd2YIubgTm6+X0UGvFTaoDqMYG1z4eRjf0UBlO99QZCAa41WKIriWBXD2izKxllefZE8C5+GSC66CdIVeGMvy6DhXeze05/JylryPmNnmtp7Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
