apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDPzU1m+tTzPWIBox/nAfMG74o9IjWJV4z9+/aG86Ai1UH9oLoPhpCwU1Gav7sJzaVy17Vm2WmyZQn3EPtWkVoy5fYaJEt9WELWzE0CMcCvDe0aPxS2DbwXV/3NhzY/HKczHdWL4wVlTTNeBCYiZ+FpPVjE+lZhuVWj9NKbSd/fGfP7Tp9RX1e0Bxi1K4ZTdb0vLL2FDfVAdUcvrwNLjwRFsTig9cmI/uR3HevM3kVQ/aT3GrNSmWpFLcbtYbRLj2958LlZqwfUBZHnbhPbGC1lpi+ggzueiCUnE0gQNIZpQq571zHgzI9IYRhQIekUHmpojAScAMUVT73NsEKf2cpaJSDw9cB4hBXWpVGYP0/gqxMT6+mLlYkfiuBptO/dTyM5ZHq/zJm/jq+Tz/3cUrJRXqXMQg6mE9MxDsoJRn7AQQJRSlpIT3fNEkHkAsWBEaFTQRT/UB9nE9D5Y5OYtRjnsYbetTVyW/QSOFkCS7g3Ftd8IIouz7VVKfa6eW9wZQ0/bLYZhOBFGsqzY57DaQOz51rhZjMTC/xO59SmtR2cZ/R/WXPVpadRyGo+E97EnI8qMtJA4z8ReYPlHWvcNLcDchKu5QSnejcbwWSgd7zGJ1i+CIe5MJoGoBk7FDNYJbvY843ZlmLMJztRncgCwInIgWmklAySpopWl0mFFTkp0roPVJBPihfKqr0JurWQUC1uNzV9Yy7iOixAICzyWHL7tooB9A==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
